
version: "3"

services:
  rchain:
    build:
      context: ./rnode
      args:
        # image_tag: release-rnode-v${RNODE_RELEASE}
        image_tag: testing
    volumes:
      - .:/app
    working_dir: /app
